version: 1.9.7.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master

skip_tags: true

configuration:
- Debug
- Release
platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

cache: packages -> **\packages.config

before_build:
- cmd: git submodule update --init --recursive

build_script:
- cmd: |-
    dotnet publish .\DOLServer\ -c %CONFIGURATION% -r win-x64 --self-contained true -o bin\win-x64
    dotnet publish .\DOLServer\ -c %CONFIGURATION% -r linux-x64 --self-contained true -o bin\linux-x64
    dotnet publish .\DOLServer\ -c %CONFIGURATION% -r linux-arm --self-contained true -o bin\linux-arm

after_build:
- cmd: |-
    7z a -tzip DOLServer_win-x64_netcore2.2_%CONFIGURATION%.zip DOLServer\bin\win-x64\*
    7z a -tzip DOLServer_linux-x64_netcore2.2_%CONFIGURATION%.zip DOLServer\bin\linux-x64\*
    7z a -tzip DOLServer_linux-arm_netcore2.2_%CONFIGURATION%.zip DOLServer\bin\linux-arm\*

artifacts:
- path: '*.zip'
  name: Release

deploy:
- provider: GitHub
  auth_token:
    secure: 0D/RfRV/f6GheHsPAdrIJRQT4C3EGC064X1xbq4DSzQWK5s9J/7Et4HV/51ozVe3
  artifact: Release
